services:
  mysql-db:
    image: mysql:8.2
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: Wannabe1231!!
      MYSQL_DATABASE: onion-db
      MYSQL_USER: onion-user
      MYSQL_PASSWORD: Wannabe1231!!
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    container_name: onion_mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ELASTIC_PASSWORD=Wannabe1231
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elastic

volumes:
  es_data:
  db_data:
    driver: local

networks:
  elastic:
    driver: bridge
