services:
  mysql-db:
    image: mysql:8.2
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: Wannabe1231!!
      MYSQL_DATABASE: onion-db
      MYSQL_USER: onion-user
      MYSQL_PASSWORD: Wannabe1231!!
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    container_name: onion_mysql
volumes:
  db_data:
