spring:
  application:
    name: backend
  datasource:
    url: 
    username: 
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 상용에서는 절대 x

jwt:
  secret: 
  expiration: 3600000


